package model;

import java.awt.Point;
import java.awt.image.BufferedImage;

import model.element.entity.Entity;
import model.element.entity.Runner;

public abstract class Gift extends Entity{
	protected Runner player;
		
		public Gift( BufferedImage img) {
			
			super(img);
			player = Runner.getRunner();
			
		}

		@Override
		public void tick() {
			// TODO Autogenerated method stub
			
		}
	
	
}
